name: morphicons_workspace
publish_to: none

environment:
  sdk: ^3.6.0

workspace:
  - packages/morphicons_core
  - packages/morphicons_flutter
  - packages/morphicons_lucide
  - packages/morphicons_tabler
  - packages/morphicons_heroicons
  - packages/morphicons_example
  - packages/morphicons_site_demo
