import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import vm from 'node:vm';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const catalogFile = resolve(__dirname, '../website/assets/lucide-catalog.js');
const dartFile = resolve(__dirname, '../packages/morphicons_lucide/lib/icons.dart');

const [catalogSource, dartSource] = await Promise.all([
  readFile(catalogFile, 'utf8'),
  readFile(dartFile, 'utf8'),
]);

assert.match(catalogSource, /^\/\/ GENERATED by tool\/export_web_lucide\.mjs/m);

const sandbox = { window: {} };
vm.runInNewContext(catalogSource, sandbox, { filename: catalogFile });
const catalog = sandbox.window.LucideCatalog;
const names = Object.keys(catalog);

assert.equal(names.length, 1565, 'catalog must contain exactly 1,565 icons');
assert.deepEqual(names, [...names].sort((a, b) => a.localeCompare(b)), 'catalog keys must be sorted');

const expected = [
  ['menu', 'menu'],
  ['x', 'x'],
  ['check', 'check'],
  ['arrowRight', 'arrow-right'],
  ['plus', 'plus'],
];

for (const [dartName, webName] of expected) {
  const match = dartSource.match(
    new RegExp(`static const String ${dartName} = "([^"]*)";`),
  );
  assert.ok(match, `Dart constant ${dartName} must exist`);
  assert.equal(catalog[webName], match[1], `${webName} must match Dart exactly`);
  console.log(`PASS ${webName}: exact Dart parity`);
}

console.log(`PASS catalog: ${names.length} sorted icons; generated header present`);
