// GENERATED pipeline: reads the installed lucide package and emits the
// browser catalog used by the Morphicons Flutter playground.

import { readdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const OUT_FILE = resolve(__dirname, '../website/assets/lucide-catalog.js');
const lucidePackageUrl = import.meta.resolve('lucide/package.json');
const iconsDirectoryUrl = new URL('dist/esm/icons/', lucidePackageUrl);

function number(value, fallback = 0) {
  if (value === undefined || value === null || value === '') return fallback;
  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : fallback;
}

function parsePoints(value) {
  return String(value || '')
    .trim()
    .split(/[\s,]+/)
    .map(Number)
    .filter(Number.isFinite);
}

function circleToPath(attrs) {
  const cx = number(attrs.cx);
  const cy = number(attrs.cy);
  const r = number(attrs.r);
  if (r <= 0) return '';
  return `M${cx - r} ${cy}A${r} ${r} 0 1 0 ${cx + r} ${cy}A${r} ${r} 0 1 0 ${cx - r} ${cy}`;
}

function ellipseToPath(attrs) {
  const cx = number(attrs.cx);
  const cy = number(attrs.cy);
  const rx = number(attrs.rx);
  const ry = number(attrs.ry);
  if (rx <= 0 || ry <= 0) return '';
  return `M${cx - rx} ${cy}A${rx} ${ry} 0 1 0 ${cx + rx} ${cy}A${rx} ${ry} 0 1 0 ${cx - rx} ${cy}`;
}

function lineToPath(attrs) {
  return `M${number(attrs.x1)} ${number(attrs.y1)}L${number(attrs.x2)} ${number(attrs.y2)}`;
}

function pointsToPath(attrs, close) {
  const values = parsePoints(attrs.points);
  if (values.length < 4) return '';
  let d = `M${values[0]} ${values[1]}`;
  for (let i = 2; i + 1 < values.length; i += 2) d += `L${values[i]} ${values[i + 1]}`;
  return close ? `${d}Z` : d;
}

function rectToPath(attrs) {
  const x = number(attrs.x);
  const y = number(attrs.y);
  const width = number(attrs.width);
  const height = number(attrs.height);
  if (width <= 0 || height <= 0) return '';

  let rx = attrs.rx === undefined ? Number.NaN : number(attrs.rx);
  let ry = attrs.ry === undefined ? Number.NaN : number(attrs.ry);
  if (Number.isNaN(rx) && Number.isNaN(ry)) rx = ry = 0;
  else if (Number.isNaN(ry)) ry = rx;
  else if (Number.isNaN(rx)) rx = ry;
  rx = Math.min(Math.max(0, rx), width / 2);
  ry = Math.min(Math.max(0, ry), height / 2);

  if (rx === 0 || ry === 0) return `M${x} ${y}h${width}v${height}h${-width}Z`;
  return `M${x + rx} ${y}h${width - 2 * rx}` +
    `a${rx} ${ry} 0 0 1 ${rx} ${ry}v${height - 2 * ry}` +
    `a${rx} ${ry} 0 0 1 ${-rx} ${ry}h${-(width - 2 * rx)}` +
    `a${rx} ${ry} 0 0 1 ${-rx} ${-ry}v${-(height - 2 * ry)}` +
    `a${rx} ${ry} 0 0 1 ${rx} ${-ry}Z`;
}

function primitiveToPath(tag, attrs = {}) {
  switch (String(tag).toLowerCase()) {
    case 'path': return String(attrs.d || '').trim();
    case 'line': return lineToPath(attrs);
    case 'circle': return circleToPath(attrs);
    case 'ellipse': return ellipseToPath(attrs);
    case 'rect': return rectToPath(attrs);
    case 'polyline': return pointsToPath(attrs, false);
    case 'polygon': return pointsToPath(attrs, true);
    default: return null;
  }
}

function flattenIconNode(nodes) {
  return nodes
    .filter((node) => Array.isArray(node) && node.length >= 2)
    .map(([tag, attrs]) => primitiveToPath(tag, attrs || {}))
    .filter((d) => d !== null && d !== '')
    .map((d) => `M0 0${d}`)
    .join(' ');
}

async function loadDefaultIcon(fileName) {
  const module = await import(new URL(fileName, iconsDirectoryUrl).href);
  if (!Array.isArray(module.default)) throw new Error('default export is not an IconNode array');
  return module.default;
}

async function main() {
  const files = (await readdir(iconsDirectoryUrl))
    .filter((name) => /\.(?:js|mjs)$/.test(name) && !name.endsWith('.map'))
    .sort((a, b) => a.localeCompare(b));
  const catalog = [];
  const skipped = [];

  for (const fileName of files) {
    const name = fileName.replace(/\.(?:js|mjs)$/, '');
    try {
      const d = flattenIconNode(await loadDefaultIcon(fileName));
      if (!d) {
        skipped.push(name);
        continue;
      }
      catalog.push([name, d]);
    } catch (error) {
      skipped.push(`${name} (${error.message})`);
    }
  }

  catalog.sort(([a], [b]) => a.localeCompare(b));
  const entries = catalog
    .map(([name, d]) => `  ${JSON.stringify(name)}: ${JSON.stringify(d)}`)
    .join(',\n');
  const output = [
    '// GENERATED by tool/export_web_lucide.mjs — do not edit by hand.',
    `// Lucide source: ${catalog.length} flattened icons; ISC licensed upstream data.`,
    'window.LucideCatalog = {',
    entries,
    '};',
    '',
  ].join('\n');

  await writeFile(OUT_FILE, output, 'utf8');
  console.log(`Generated ${catalog.length} icons in ${OUT_FILE}`);
  if (skipped.length) console.log(`Skipped ${skipped.length} icon(s): ${skipped.join(', ')}`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
