// GENERATED pipeline: reads the npm '@tabler/icons' package and emits
// packages/morphicons_tabler/lib/icons.dart as plain Dart const data.
//
// Tabler outline icons are 24×24 stroke with uniform 2px stroke, round
// caps/joins — exactly the canonical grid morphicons_core expects. Unlike
// a 16×16 or 20×20 pack that needs fitIcon scaling, Tabler can be fed
// directly to parsePath → normalize → resample without any viewBox
// transform. We only need to:
//  - drop the invisible 24×24 background rect (d="M0 0h24v24H0z"),
//  - flatten the tiny filled dots (<circle r=".5">) and the single <rect>
//    (binoculars) into path data, joining every element with an anchored
//    "M0 0" so relative "m" moves don't bleed across concatenated subpaths,
//    just like extract_icons.mjs does for Lucide.

import { readFile, readdir, writeFile, mkdir } from "node:fs/promises";
import { dirname, resolve, join, basename } from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const OUT_FILE = resolve(__dirname, "../packages/morphicons_tabler/lib/icons.dart");
const ICONS_DIR = resolve(__dirname, "node_modules/@tabler/icons/icons/outline");
const HEADER = "// GENERATED by tool/extract_tabler.mjs — do not edit by hand.\n";

const DART_KEYWORDS = new Set([
  "assert", "break", "case", "catch", "class", "const", "continue", "default",
  "do", "else", "enum", "extends", "false", "final", "finally", "for", "if",
  "in", "is", "new", "null", "rethrow", "return", "super", "switch", "this",
  "throw", "true", "try", "var", "void", "while", "with",
]);

function toCamelCase(kebab) {
  const parts = kebab.split("-");
  const first = parts[0];
  const rest = parts
    .slice(1)
    .map((p) => (p ? p[0].toUpperCase() + p.slice(1) : ""));
  let id = first + rest.join("");
  if (!id || /^[0-9]/.test(id)) {
    id = "icon" + id[0].toUpperCase() + id.slice(1);
  }
  if (DART_KEYWORDS.has(id)) {
    id = id + "Icon";
  }
  return id;
}

function num(value, fallback = 0) {
  if (value === undefined || value === null || value === "") return fallback;
  const n = Number(value);
  return Number.isFinite(n) ? n : fallback;
}

function circleToPath(attrs) {
  const cx = num(attrs.cx);
  const cy = num(attrs.cy);
  const r = num(attrs.r);
  if (r <= 0) return "";
  return `M${cx - r} ${cy}A${r} ${r} 0 1 0 ${cx + r} ${cy}A${r} ${r} 0 1 0 ${cx - r} ${cy}`;
}

function ellipseToPath(attrs) {
  const cx = num(attrs.cx);
  const cy = num(attrs.cy);
  const rx = num(attrs.rx);
  const ry = num(attrs.ry);
  if (rx <= 0 || ry <= 0) return "";
  return `M${cx - rx} ${cy}A${rx} ${ry} 0 1 0 ${cx + rx} ${cy}A${rx} ${ry} 0 1 0 ${cx - rx} ${cy}`;
}

function lineToPath(attrs) {
  const x1 = num(attrs.x1);
  const y1 = num(attrs.y1);
  const x2 = num(attrs.x2);
  const y2 = num(attrs.y2);
  return `M${x1} ${y1}L${x2} ${y2}`;
}

function parsePoints(pointsStr) {
  if (!pointsStr) return [];
  return pointsStr
    .trim()
    .split(/[\s,]+/)
    .map((s) => Number(s))
    .filter((n) => Number.isFinite(n));
}

function polylineToPath(attrs, close = false) {
  const pts = parsePoints(attrs.points);
  if (pts.length < 2) return "";
  const pairs = [];
  for (let i = 0; i < pts.length; i += 2) {
    pairs.push([pts[i], pts[i + 1]]);
  }
  const first = pairs[0];
  let d = `M${first[0]} ${first[1]}`;
  for (let i = 1; i < pairs.length; i++) {
    d += `L${pairs[i][0]} ${pairs[i][1]}`;
  }
  if (close) d += "Z";
  return d;
}

function rectToPath(attrs) {
  const x = num(attrs.x);
  const y = num(attrs.y);
  const w = num(attrs.width);
  const h = num(attrs.height);
  if (w <= 0 || h <= 0) return "";

  let rx = num(attrs.rx, Number.NaN);
  let ry = num(attrs.ry, Number.NaN);
  if (Number.isNaN(rx) && Number.isNaN(ry)) {
    rx = 0;
    ry = 0;
  } else if (Number.isNaN(ry)) {
    ry = rx;
  } else if (Number.isNaN(rx)) {
    rx = ry;
  }
  rx = Math.min(Math.max(0, rx), w / 2);
  ry = Math.min(Math.max(0, ry), h / 2);

  if (rx === 0 || ry === 0) {
    return `M${x} ${y}h${w}v${h}h${-w}Z`;
  }

  return (
    `M${x + rx} ${y}` +
    `h${w - 2 * rx}` +
    `a${rx} ${ry} 0 0 1 ${rx} ${ry}` +
    `v${h - 2 * ry}` +
    `a${rx} ${ry} 0 0 1 ${-rx} ${ry}` +
    `h${-(w - 2 * rx)}` +
    `a${rx} ${ry} 0 0 1 ${-rx} ${-ry}` +
    `v${-(h - 2 * ry)}` +
    `a${rx} ${ry} 0 0 1 ${rx} ${-ry}` +
    "Z"
  );
}

function elementToPath(tag, attrs) {
  switch (tag) {
    case "path":
      return attrs.d || "";
    case "circle":
      return circleToPath(attrs);
    case "ellipse":
      return ellipseToPath(attrs);
    case "line":
      return lineToPath(attrs);
    case "polyline":
      return polylineToPath(attrs, false);
    case "polygon":
      return polylineToPath(attrs, true);
    case "rect":
      return rectToPath(attrs);
    default:
      return null;
  }
}

function parseAttrs(attrStr) {
  const attrs = {};
  const re = /([\w:-]+)\s*=\s*"([^"]*)"/g;
  let m;
  while ((m = re.exec(attrStr)) !== null) {
    attrs[m[1]] = m[2];
  }
  const re2 = /([\w:-]+)\s*=\s*'([^']*)'/g;
  while ((m = re2.exec(attrStr)) !== null) {
    if (!(m[1] in attrs)) attrs[m[1]] = m[2];
  }
  return attrs;
}

async function main() {
  const entries = await readdir(ICONS_DIR);
  const svgFiles = entries.filter((n) => n.endsWith(".svg")).sort();

  const rows = [];
  const skippedIcons = [];

  for (const fileName of svgFiles) {
    const kebabName = basename(fileName, ".svg");
    const dartName = toCamelCase(kebabName);
    const svg = await readFile(join(ICONS_DIR, fileName), "utf8");

    // Capture <path>, <circle>, <rect>, <ellipse>, <line>, <polyline>, <polygon>
    // in document order so filled dots interleave correctly. The dummy
    // background path (M0 0h24v24H0z, stroke="none") is skipped — it is not
    // part of the icon stroke, just the 24×24 canvas marker.
    const tagRe = /<(path|circle|rect|ellipse|line|polyline|polygon)\b([^>]*?)\/?>/g;
    const ds = [];
    let anySkipped = false;
    let m;
    while ((m = tagRe.exec(svg)) !== null) {
      const tag = m[1];
      const attrStr = m[2];
      const attrs = parseAttrs(attrStr);
      let d;
      if (tag === "path") {
        d = attrs.d || "";
        if (!d || d === "M0 0h24v24H0z") continue;
      } else {
        d = elementToPath(tag, attrs);
        if (d === null) {
          anySkipped = true;
          console.error(`SKIP element in ${kebabName}: unsupported tag "${tag}"`);
          continue;
        }
      }
      if (d) {
        // Anchor every element at the origin — see extract_icons.mjs for why.
        // Tabler's d's frequently start with "M12 12m-9 0a9 9 ..." where the
        // "m" is relative to the preceding "M". Without the M0 0 anchor the
        // current point after the previous icon element would leak into the
        // next relative move. The empty moveto is elided by the parser.
        ds.push(`M0 0${d}`);
      }
    }

    if (anySkipped) skippedIcons.push(kebabName);

    if (ds.length === 0) {
      console.error(`SKIP ${kebabName}: no path data produced`);
      if (!anySkipped) skippedIcons.push(kebabName);
      continue;
    }

    rows.push({ kebabName, dartName, d: ds.join(" ") });
  }

  // Deduplicate identifiers.
  const seenIds = new Set();
  for (const row of rows) {
    if (seenIds.has(row.dartName)) {
      let i = 2;
      while (seenIds.has(`${row.dartName}${i}`)) i++;
      row.dartName = `${row.dartName}${i}`;
    }
    seenIds.add(row.dartName);
  }

  const dartBody = rows
    .map((r) => `  /// Tabler icon \`${r.kebabName}\` (24x24 stroke paths).\n  static const String ${r.dartName} = "${r.d}";`)
    .join("\n");

  const mapBody = rows
    .map((r) => `  "${r.kebabName}": MorphIconsTabler.${r.dartName},`)
    .join("\n");

  const output =
    HEADER +
    "\n" +
    "/// Tabler icon path data.\n" +
    "class MorphIconsTabler {\n" +
    dartBody +
    "\n}\n" +
    "\n" +
    "/// Map of kebab-case Tabler icon names to their path data.\n" +
    "const Map<String, String> tablerIcons = {\n" +
    mapBody +
    "\n};\n";

  await mkdir(dirname(OUT_FILE), { recursive: true });
  await writeFile(OUT_FILE, output, "utf8");

  console.log(`Generated ${rows.length} icons in ${OUT_FILE}`);
  if (skippedIcons.length > 0) {
    console.log(`Skipped ${skippedIcons.length} icon(s): ${[...new Set(skippedIcons)].join(", ")}`);
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
