// GENERATED pipeline: reads the npm 'lucide' package and emits
// packages/morphicons_lucide/lib/icons.dart as plain Dart const data.

import { readFile, readdir, writeFile, mkdir } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const OUT_FILE = resolve(__dirname, "../packages/morphicons_lucide/lib/icons.dart");
const HEADER = "// GENERATED by tool/extract_icons.mjs — do not edit by hand.\n";

// Resolve the installed lucide package root robustly.
const lucidePkgUrl = import.meta.resolve("lucide/package.json");
const lucidePkgPath = fileURLToPath(lucidePkgUrl);
const iconsDirUrl = new URL("dist/esm/icons/", lucidePkgUrl);

const DART_KEYWORDS = new Set([
  "assert", "break", "case", "catch", "class", "const", "continue", "default",
  "do", "else", "enum", "extends", "false", "final", "finally", "for", "if",
  "in", "is", "new", "null", "rethrow", "return", "super", "switch", "this",
  "throw", "true", "try", "var", "void", "while", "with",
]);

function toCamelCase(kebab) {
  const parts = kebab.split("-");
  const first = parts[0];
  const rest = parts
    .slice(1)
    .map((p) => (p ? p[0].toUpperCase() + p.slice(1) : ""));
  let id = first + rest.join("");
  if (!id || /^[0-9]/.test(id)) {
    id = "icon" + id[0].toUpperCase() + id.slice(1);
  }
  if (DART_KEYWORDS.has(id)) {
    id = id + "Icon";
  }
  return id;
}

function num(value, fallback = 0) {
  if (value === undefined || value === null || value === "") return fallback;
  const n = Number(value);
  return Number.isFinite(n) ? n : fallback;
}

function circleToPath(attrs) {
  const cx = num(attrs.cx);
  const cy = num(attrs.cy);
  const r = num(attrs.r);
  if (r <= 0) return "";
  return `M${cx - r} ${cy}A${r} ${r} 0 1 0 ${cx + r} ${cy}A${r} ${r} 0 1 0 ${cx - r} ${cy}`;
}

function ellipseToPath(attrs) {
  const cx = num(attrs.cx);
  const cy = num(attrs.cy);
  const rx = num(attrs.rx);
  const ry = num(attrs.ry);
  if (rx <= 0 || ry <= 0) return "";
  return `M${cx - rx} ${cy}A${rx} ${ry} 0 1 0 ${cx + rx} ${cy}A${rx} ${ry} 0 1 0 ${cx - rx} ${cy}`;
}

function lineToPath(attrs) {
  const x1 = num(attrs.x1);
  const y1 = num(attrs.y1);
  const x2 = num(attrs.x2);
  const y2 = num(attrs.y2);
  return `M${x1} ${y1}L${x2} ${y2}`;
}

function parsePoints(pointsStr) {
  if (!pointsStr) return [];
  return pointsStr
    .trim()
    .split(/[\s,]+/)
    .map((s) => Number(s))
    .filter((n) => Number.isFinite(n));
}

function polylineToPath(attrs, close = false) {
  const pts = parsePoints(attrs.points);
  if (pts.length < 2) return "";
  const pairs = [];
  for (let i = 0; i < pts.length; i += 2) {
    pairs.push([pts[i], pts[i + 1]]);
  }
  const first = pairs[0];
  let d = `M${first[0]} ${first[1]}`;
  for (let i = 1; i < pairs.length; i++) {
    d += `L${pairs[i][0]} ${pairs[i][1]}`;
  }
  if (close) d += "Z";
  return d;
}

function rectToPath(attrs) {
  const x = num(attrs.x);
  const y = num(attrs.y);
  const w = num(attrs.width);
  const h = num(attrs.height);
  if (w <= 0 || h <= 0) return "";

  let rx = num(attrs.rx, Number.NaN);
  let ry = num(attrs.ry, Number.NaN);
  if (Number.isNaN(rx) && Number.isNaN(ry)) {
    rx = 0;
    ry = 0;
  } else if (Number.isNaN(ry)) {
    ry = rx;
  } else if (Number.isNaN(rx)) {
    rx = ry;
  }
  rx = Math.min(Math.max(0, rx), w / 2);
  ry = Math.min(Math.max(0, ry), h / 2);

  if (rx === 0 || ry === 0) {
    return `M${x} ${y}h${w}v${h}h${-w}Z`;
  }

  return (
    `M${x + rx} ${y}` +
    `h${w - 2 * rx}` +
    `a${rx} ${ry} 0 0 1 ${rx} ${ry}` +
    `v${h - 2 * ry}` +
    `a${rx} ${ry} 0 0 1 ${-rx} ${ry}` +
    `h${-(w - 2 * rx)}` +
    `a${rx} ${ry} 0 0 1 ${-rx} ${-ry}` +
    `v${-(h - 2 * ry)}` +
    `a${rx} ${ry} 0 0 1 ${rx} ${-ry}` +
    "Z"
  );
}

function elementToPath(tag, attrs) {
  switch (tag) {
    case "path":
      return attrs.d || "";
    case "circle":
      return circleToPath(attrs);
    case "ellipse":
      return ellipseToPath(attrs);
    case "line":
      return lineToPath(attrs);
    case "polyline":
      return polylineToPath(attrs, false);
    case "polygon":
      return polylineToPath(attrs, true);
    case "rect":
      return rectToPath(attrs);
    default:
      return null;
  }
}

async function loadIconData(fileUrl) {
  const mod = await import(fileUrl.href);
  const data = mod.default;
  if (!Array.isArray(data)) {
    throw new Error(`expected IconNode array, got ${typeof data}`);
  }
  return data;
}

async function main() {
  const entries = await readdir(iconsDirUrl);
  const iconFiles = entries
    .filter((name) => (name.endsWith(".js") || name.endsWith(".mjs")) && !name.endsWith(".map"))
    .sort();

  const rows = [];
  const skippedIcons = [];

  for (const fileName of iconFiles) {
    const kebabName = fileName.replace(/\.(mjs|js)$/, "");
    const dartName = toCamelCase(kebabName);
    const fileUrl = new URL(fileName, iconsDirUrl);

    let data;
    try {
      data = await loadIconData(fileUrl);
    } catch (err) {
      console.error(`SKIP ${kebabName}: import failed — ${err.message}`);
      skippedIcons.push(kebabName);
      continue;
    }

    const ds = [];
    let anySkipped = false;
    for (const node of data) {
      if (!Array.isArray(node) || node.length < 2) {
        anySkipped = true;
        console.error(`SKIP element in ${kebabName}: malformed node ${JSON.stringify(node)}`);
        continue;
      }
      const [tag, attrs] = node;
      let d = elementToPath(tag, attrs || {});
      if (d === null) {
        anySkipped = true;
        console.error(`SKIP element in ${kebabName}: unsupported tag "${tag}"`);
        continue;
      }
      if (d) {
        // Lucide sometimes exports element d strings starting with a relative
        // command (e.g. "m6 6 12 12"). Alone that is relative to (0,0), but
        // concatenated after another element the current point would be wrong.
        // Anchor every element at the origin first; the empty moveto subpath
        // is dropped by any conforming parser (and by morphicons_core).
        ds.push(`M0 0${d}`);
      }
    }

    if (anySkipped) {
      skippedIcons.push(kebabName);
    }

    if (ds.length === 0) {
      console.error(`SKIP ${kebabName}: no path data produced`);
      if (!anySkipped) skippedIcons.push(kebabName);
      continue;
    }

    rows.push({ kebabName, dartName, d: ds.join(" ") });
  }

  // Deduplicate identifiers (shouldn't happen, but guard against collisions).
  const seenIds = new Set();
  for (const row of rows) {
    if (seenIds.has(row.dartName)) {
      let i = 2;
      while (seenIds.has(`${row.dartName}${i}`)) i++;
      row.dartName = `${row.dartName}${i}`;
    }
    seenIds.add(row.dartName);
  }

  const dartBody = rows
    .map((r) => `  /// Lucide icon \`${r.kebabName}\` (24x24 stroke paths).\n  static const String ${r.dartName} = "${r.d}";`)
    .join("\n");

  const mapBody = rows
    .map((r) => `  "${r.kebabName}": MorphIconsLucide.${r.dartName},`)
    .join("\n");

  const output =
    HEADER +
    "\n" +
    "/// Lucide icon path data.\n" +
    "class MorphIconsLucide {\n" +
    dartBody +
    "\n}\n" +
    "\n" +
    "/// Map of kebab-case Lucide icon names to their path data.\n" +
    "const Map<String, String> lucideIcons = {\n" +
    mapBody +
    "\n};\n";

  await mkdir(dirname(OUT_FILE), { recursive: true });
  await writeFile(OUT_FILE, output, "utf8");

  console.log(`Generated ${rows.length} icons in ${OUT_FILE}`);
  if (skippedIcons.length > 0) {
    console.log(`Skipped ${skippedIcons.length} icon(s): ${[...new Set(skippedIcons)].join(", ")}`);
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
