// GENERATED pipeline: reads the npm 'heroicons' package and emits
// packages/morphicons_heroicons/lib/icons.dart as plain Dart const data.
//
// Heroicons ships as raw SVG files under heroicons/24/outline, 24/solid,
// 20/solid and 16/solid. Outline is 24×24 stroke (1.5px, round caps —
// directly on morphicons_core's canonical 24 grid like Lucide/Tabler).
// Solid is 20×20 (classic) or 24×24 / 16×16 (heroicons 2.x) filled with
// fill-rule evenodd. Solid 20×20 and 16×16 do NOT sit on the 24 grid;
// mixing them unfitted with outline makes Procrustes read the scale gap
// as rotation (see morphicons_core fitIcon). We therefore re-grid solid
// 20 and 16 to 24 at generation time via uniform scale (×1.2 and ×1.5,
// xMidYMid meet), so every emitted d string is already on 24×24 and
// can be passed directly to parsePath/iconToCubics without per-render
// fitIcon. 24/outline and 24/solid need no transform.
//
// Stroke vs fill is purely visual — both become path data. Outline's
// stroke becomes thin path geometry (stroke-width is baking into the
// path's shape via the designer's coordinates); solid's fill becomes
// closed evenodd shapes. Morphicons renders either via fill, so no
// special casing is needed beyond preserving the path d as-is.
//
// Every element's d is anchored with "M0 0" before joining — see
// extract_icons.mjs for why Lucide needs it (relative "m" after a
// different current point). Heroicons outline paths also start with
// "M" but solid paths contain relative "a"/"c" after the first move;
// prefixing "M0 0" makes each subpath start from the origin in an
// empty moveto that the parser drops, so concatenation is order-
// independent and idempotent.

import { readFile, readdir, writeFile, mkdir } from "node:fs/promises";
import { dirname, resolve, join, basename } from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const OUT_FILE = resolve(__dirname, "../packages/morphicons_heroicons/lib/icons.dart");
const HEADER = "// GENERATED by tool/extract_heroicons.mjs — do not edit by hand.\n";

// Resolve heroicons package root robustly.
const heroPkgUrl = import.meta.resolve("heroicons/package.json");
const heroPkgRoot = fileURLToPath(new URL(".", heroPkgUrl));

const DART_KEYWORDS = new Set([
  "assert", "break", "case", "catch", "class", "const", "continue", "default",
  "do", "else", "enum", "extends", "false", "final", "finally", "for", "if",
  "in", "is", "new", "null", "rethrow", "return", "super", "switch", "this",
  "throw", "true", "try", "var", "void", "while", "with",
]);

function toCamelCase(kebab) {
  const parts = kebab.split("-");
  const first = parts[0];
  const rest = parts
    .slice(1)
    .map((p) => (p ? p[0].toUpperCase() + p.slice(1) : ""));
  let id = first + rest.join("");
  if (!id || /^[0-9]/.test(id)) {
    id = "icon" + id[0].toUpperCase() + id.slice(1);
  }
  if (DART_KEYWORDS.has(id)) {
    id = id + "Icon";
  }
  return id;
}

function num(value, fallback = 0) {
  if (value === undefined || value === null || value === "") return fallback;
  const n = Number(value);
  return Number.isFinite(n) ? n : fallback;
}

function circleToPath(attrs) {
  const cx = num(attrs.cx);
  const cy = num(attrs.cy);
  const r = num(attrs.r);
  if (r <= 0) return "";
  return `M${cx - r} ${cy}A${r} ${r} 0 1 0 ${cx + r} ${cy}A${r} ${r} 0 1 0 ${cx - r} ${cy}`;
}

function ellipseToPath(attrs) {
  const cx = num(attrs.cx);
  const cy = num(attrs.cy);
  const rx = num(attrs.rx);
  const ry = num(attrs.ry);
  if (rx <= 0 || ry <= 0) return "";
  return `M${cx - rx} ${cy}A${rx} ${ry} 0 1 0 ${cx + rx} ${cy}A${rx} ${ry} 0 1 0 ${cx - rx} ${cy}`;
}

function lineToPath(attrs) {
  const x1 = num(attrs.x1);
  const y1 = num(attrs.y1);
  const x2 = num(attrs.x2);
  const y2 = num(attrs.y2);
  return `M${x1} ${y1}L${x2} ${y2}`;
}

function parsePoints(pointsStr) {
  if (!pointsStr) return [];
  return pointsStr
    .trim()
    .split(/[\s,]+/)
    .map((s) => Number(s))
    .filter((n) => Number.isFinite(n));
}

function polylineToPath(attrs, close = false) {
  const pts = parsePoints(attrs.points);
  if (pts.length < 2) return "";
  const pairs = [];
  for (let i = 0; i < pts.length; i += 2) {
    pairs.push([pts[i], pts[i + 1]]);
  }
  const first = pairs[0];
  let d = `M${first[0]} ${first[1]}`;
  for (let i = 1; i < pairs.length; i++) {
    d += `L${pairs[i][0]} ${pairs[i][1]}`;
  }
  if (close) d += "Z";
  return d;
}

function rectToPath(attrs) {
  const x = num(attrs.x);
  const y = num(attrs.y);
  const w = num(attrs.width);
  const h = num(attrs.height);
  if (w <= 0 || h <= 0) return "";

  let rx = num(attrs.rx, Number.NaN);
  let ry = num(attrs.ry, Number.NaN);
  if (Number.isNaN(rx) && Number.isNaN(ry)) {
    rx = 0;
    ry = 0;
  } else if (Number.isNaN(ry)) {
    ry = rx;
  } else if (Number.isNaN(rx)) {
    rx = ry;
  }
  rx = Math.min(Math.max(0, rx), w / 2);
  ry = Math.min(Math.max(0, ry), h / 2);

  if (rx === 0 || ry === 0) {
    return `M${x} ${y}h${w}v${h}h${-w}Z`;
  }

  return (
    `M${x + rx} ${y}` +
    `h${w - 2 * rx}` +
    `a${rx} ${ry} 0 0 1 ${rx} ${ry}` +
    `v${h - 2 * ry}` +
    `a${rx} ${ry} 0 0 1 ${-rx} ${ry}` +
    `h${-(w - 2 * rx)}` +
    `a${rx} ${ry} 0 0 1 ${-rx} ${-ry}` +
    `v${-(h - 2 * ry)}` +
    `a${rx} ${ry} 0 0 1 ${rx} ${-ry}` +
    "Z"
  );
}

function elementToPath(tag, attrs) {
  switch (tag) {
    case "path":
      return attrs.d || "";
    case "circle":
      return circleToPath(attrs);
    case "ellipse":
      return ellipseToPath(attrs);
    case "line":
      return lineToPath(attrs);
    case "polyline":
      return polylineToPath(attrs, false);
    case "polygon":
      return polylineToPath(attrs, true);
    case "rect":
      return rectToPath(attrs);
    default:
      return null;
  }
}

function parseAttrs(attrStr) {
  const attrs = {};
  const re = /([\w:-]+)\s*=\s*"([^"]*)"/g;
  let m;
  while ((m = re.exec(attrStr)) !== null) {
    attrs[m[1]] = m[2];
  }
  const re2 = /([\w:-]+)\s*=\s*'([^']*)'/g;
  while ((m = re2.exec(attrStr)) !== null) {
    if (!(m[1] in attrs)) attrs[m[1]] = m[2];
  }
  return attrs;
}

// ViewBox handling: parse "0 0 w h" (or "0 0 w" -> square).
function parseViewBox(vbStr) {
  if (!vbStr) return [0, 0, 24, 24];
  const parts = vbStr.trim().split(/[\s,]+/).map(Number).filter((n) => Number.isFinite(n));
  if (parts.length === 4) return parts;
  if (parts.length === 2) return [0, 0, parts[0], parts[1]];
  if (parts.length === 1) return [0, 0, parts[0], parts[0]];
  return [0, 0, 24, 24];
}

// Scale an SVG path d from its viewBox onto the 24 grid.
// Implements the same xMidYMid meet as morphicons_core fitIcon, but for
// uniform scale with integer heroicons grids the tx/ty are 0 (e.g. 20->24
// is simply ×1.2). Handles absolute vs relative, flags, H/V, and implicit
// L after M. Only called when viewBox != 24.
function fmtNum(n) {
  // Round to avoid floating artefacts like 0.8999999999999999 for 0.75*1.2.
  // 4 decimal places is enough for 24-grid precision (1e-4 ≈ 0.002px at 24).
  // Trim trailing zeros via parseFloat.
  if (!Number.isFinite(n)) return String(n);
  return parseFloat(n.toFixed(4)).toString();
}

function scalePathData(d, vbW, vbH, grid = 24, minX = 0, minY = 0) {
  const s = Math.min(grid / vbW, grid / vbH);
  const tx = (grid - vbW * s) / 2 - minX * s;
  const ty = (grid - vbH * s) / 2 - minY * s;
  if (Math.abs(s - 1) < 1e-12 && Math.abs(tx) < 1e-12 && Math.abs(ty) < 1e-12) {
    return d;
  }
  const tokens = d.match(/[a-zA-Z]|[-+]?(?:\d*\.\d+|\d+\.?)(?:[eE][-+]?\d+)?/g);
  if (!tokens) return d;
  let out = "";
  let idx = 0;
  let curCmd = "";
  let rel = false;
  let segCount = 0;

  const append = (v) => {
    out += v + " ";
  };

  while (idx < tokens.length) {
    const tok = tokens[idx];
    if (/^[a-zA-Z]$/.test(tok)) {
      curCmd = tok;
      rel = curCmd !== curCmd.toUpperCase();
      // Append command without trailing space — numbers carry spacing.
      out += curCmd;
      segCount = 0;
      idx++;
      if (curCmd.toUpperCase() === "Z") {
        out += " ";
        continue;
      }
      continue;
    }
    const upper = curCmd.toUpperCase();
    // For commands without explicit curCmd yet (malformed), just copy number scaled
    if (!upper || upper === "") {
      append(fmtNum(parseFloat(tok) * s));
      idx++;
      continue;
    }
    if (upper === "A") {
      const pos = segCount % 7;
      if (pos === 0 || pos === 1) {
        // rx, ry
        append(fmtNum(parseFloat(tok) * s));
      } else if (pos === 2) {
        // x-axis-rotation
        append(tok);
      } else if (pos === 3 || pos === 4) {
        // flags
        append(tok);
      } else if (pos === 5) {
        const n = parseFloat(tok);
        append(fmtNum(rel ? n * s : n * s + tx));
      } else if (pos === 6) {
        const n = parseFloat(tok);
        append(fmtNum(rel ? n * s : n * s + ty));
      }
      segCount++;
      idx++;
    } else if (upper === "H") {
      const n = parseFloat(tok);
      append(fmtNum(rel ? n * s : n * s + tx));
      segCount++;
      idx++;
    } else if (upper === "V") {
      const n = parseFloat(tok);
      append(fmtNum(rel ? n * s : n * s + ty));
      segCount++;
      idx++;
    } else if (upper === "M" || upper === "L" || upper === "T") {
      const isX = segCount % 2 === 0;
      const n = parseFloat(tok);
      append(fmtNum(isX ? (rel ? n * s : n * s + tx) : (rel ? n * s : n * s + ty)));
      segCount++;
      if (upper === "M" && segCount === 2) {
        // After first M pair, implicit L/l
        if (idx + 1 < tokens.length && !/^[a-zA-Z]$/.test(tokens[idx + 1])) {
          curCmd = rel ? "l" : "L";
          segCount = 0;
        }
      }
      idx++;
    } else if (upper === "C") {
      const isX = segCount % 2 === 0;
      const n = parseFloat(tok);
      append(fmtNum(isX ? (rel ? n * s : n * s + tx) : (rel ? n * s : n * s + ty)));
      segCount++;
      idx++;
    } else if (upper === "S" || upper === "Q") {
      const isX = segCount % 2 === 0;
      const n = parseFloat(tok);
      append(fmtNum(isX ? (rel ? n * s : n * s + tx) : (rel ? n * s : n * s + ty)));
      segCount++;
      idx++;
    } else {
      // fallback: scale
      append(fmtNum(parseFloat(tok) * s));
      segCount++;
      idx++;
    }
  }
  // Tidy: collapse whitespace, ensure command-letter spacing is consistent
  return out.trim().replace(/\s+/g, " ").replace(/ ([a-zA-Z])/g, " $1").trim();
}

async function extractFromDir(iconsSubdir, { fitTo24 = false } = {}) {
  const dirPath = join(heroPkgRoot, iconsSubdir);
  const entries = await readdir(dirPath);
  const svgFiles = entries.filter((n) => n.endsWith(".svg")).sort();

  const rows = [];
  const skipped = [];

  for (const fileName of svgFiles) {
    const kebabName = basename(fileName, ".svg");
    const dartName = toCamelCase(kebabName);
    const svg = await readFile(join(dirPath, fileName), "utf8");

    // Extract viewBox — Heroicons uses viewBox="0 0 24 24" (outline & 24/solid),
    // "0 0 20 20" (20/solid) and "0 0 16 16" (16/solid). If missing, default 24.
    const vbMatch = svg.match(/viewBox\s*=\s*["']([^"']+)["']/);
    const vb = parseViewBox(vbMatch ? vbMatch[1] : "0 0 24 24");
    const [minX, minY, vbW, vbH] = vb;
    const needsScale = fitTo24 && (vbW !== 24 || vbH !== 24 || minX !== 0 || minY !== 0);

    // Capture elements in document order. Heroicons uses only <path>, but we
    // handle circle/rect etc generically via elementToPath (like lucide/tabler).
    const tagRe = /<(path|circle|rect|ellipse|line|polyline|polygon)\b([^>]*?)\/?>/g;
    const ds = [];
    let anySkipped = false;
    let m;
    while ((m = tagRe.exec(svg)) !== null) {
      const tag = m[1];
      const attrStr = m[2];
      const attrs = parseAttrs(attrStr);
      let d;
      if (tag === "path") {
        d = attrs.d || "";
        if (!d) continue;
      } else {
        d = elementToPath(tag, attrs);
        if (d === null) {
          anySkipped = true;
          console.error(`SKIP element in ${iconsSubdir}/${kebabName}: unsupported tag "${tag}"`);
          continue;
        }
      }
      if (!d) continue;
      // Re-grid to 24 if needed (solid 20/16). Apply before M0 0 anchoring so
      // the anchor itself stays at the origin and isn't scaled.
      if (needsScale) {
        d = scalePathData(d, vbW, vbH, 24, minX, minY);
      }
      // Anchor every element at the origin — see module header.
      ds.push(`M0 0${d}`);
    }

    if (anySkipped) skipped.push(kebabName);
    if (ds.length === 0) {
      console.error(`SKIP ${kebabName} in ${iconsSubdir}: no path data produced`);
      if (!anySkipped) skipped.push(kebabName);
      continue;
    }

    rows.push({ kebabName, dartName, d: ds.join(" ") });
  }

  // Deduplicate camelCase collisions inside this dir.
  const seen = new Set();
  for (const row of rows) {
    if (seen.has(row.dartName)) {
      let i = 2;
      while (seen.has(`${row.dartName}${i}`)) i++;
      row.dartName = `${row.dartName}${i}`;
    }
    seen.add(row.dartName);
  }

  return { rows, skipped };
}

async function main() {
  // We generate four variants. Outline 24 is the primary 24×24 stroke pack
  // (directly analogous to Lucide, no scaling). Solid 20 and 16 are fitted
  // to 24 so they can morph cleanly with outline. 24/solid is kept as-is.
  const outline = await extractFromDir("24/outline", { fitTo24: false });
  const solid20 = await extractFromDir("20/solid", { fitTo24: true });
  const solid24 = await extractFromDir("24/solid", { fitTo24: false });
  const solid16 = await extractFromDir("16/solid", { fitTo24: true });

  // Build Dart output — four classes + four maps. Primary is outline.
  const formatBody = (rows, kind) =>
    rows
      .map((r) => `  /// Heroicons ${kind} \`${r.kebabName}\`.\n  static const String ${r.dartName} = "${r.d}";`)
      .join("\n");

  const formatMap = (rows, className) =>
    rows.map((r) => `  "${r.kebabName}": ${className}.${r.dartName},`).join("\n");

  const outlineBody = formatBody(outline.rows, "24/outline (24×24 stroke)");
  const solid20Body = formatBody(solid20.rows, "20/solid (20×20 fill, fitted to 24×24)");
  const solid24Body = formatBody(solid24.rows, "24/solid (24×24 fill)");
  const solid16Body = formatBody(solid16.rows, "16/solid (16×16 fill, fitted to 24×24)");

  const outlineMap = formatMap(outline.rows, "MorphIconsHeroicons");
  const solid20Map = formatMap(solid20.rows, "MorphIconsHeroiconsSolid");
  const solid24Map = formatMap(solid24.rows, "MorphIconsHeroiconsSolid24");
  const solid16Map = formatMap(solid16.rows, "MorphIconsHeroiconsSolid16");

  const output =
    HEADER +
    "\n" +
    "/// Heroicons icon path data — generated from the npm `heroicons` package.\n" +
    "/// Outline is 24×24 stroke; solid variants are fill. Solid 20×20 and\n" +
    "/// 16×16 have been re-gridded to 24×24 (×1.2 / ×1.5) so they share the\n" +
    "/// same coordinate space as outline and can morph without an extra\n" +
    "/// fitIcon step. Use [MorphIconsHeroicons] for outline, or one of the\n" +
    "/// solid classes as needed. All paths are anchored with `M0 0` per\n" +
    "/// element to avoid relative-command bleed.\n" +
    "class MorphIconsHeroicons {\n" +
    outlineBody +
    "\n}\n" +
    "\n" +
    "/// Map of kebab-case Heroicons (24/outline) names to path data.\n" +
    "const Map<String, String> heroiconsIcons = {\n" +
    outlineMap +
    "\n};\n" +
    "\n" +
    "/// Heroicons Solid — 20×20 fill icons fitted to 24×24.\n" +
    "/// Original viewBox 0 0 20 20 scaled ×1.2 (xMidYMid meet) at generation\n" +
    "/// time via [scalePathData]. If you need the raw 20-grid data, divide\n" +
    "/// coordinates by 1.2 or call fitIcon(raw, '0 0 20 20') in Dart.\n" +
    "class MorphIconsHeroiconsSolid {\n" +
    solid20Body +
    "\n}\n" +
    "\n" +
    "/// Map of kebab-case Heroicons Solid (20) names to fitted path data.\n" +
    "const Map<String, String> heroiconsSolidIcons = {\n" +
    solid20Map +
    "\n};\n" +
    "\n" +
    "/// Heroicons Solid 24 — 24×24 fill icons (no scaling).\n" +
    "class MorphIconsHeroiconsSolid24 {\n" +
    solid24Body +
    "\n}\n" +
    "\n" +
    "/// Map of kebab-case Heroicons Solid 24 names to path data.\n" +
    "const Map<String, String> heroiconsSolid24Icons = {\n" +
    solid24Map +
    "\n};\n" +
    "\n" +
    "/// Heroicons Solid 16 — 16×16 fill icons fitted to 24×24 (×1.5).\n" +
    "class MorphIconsHeroiconsSolid16 {\n" +
    solid16Body +
    "\n}\n" +
    "\n" +
    "/// Map of kebab-case Heroicons Solid 16 names to fitted path data.\n" +
    "const Map<String, String> heroiconsSolid16Icons = {\n" +
    solid16Map +
    "\n};\n" +
    "\n" +
    "/// All Heroicons variants combined: outline + solid 20 fitted.\n" +
    "/// Uses spread so solid wins on key collision (every outline name exists\n" +
    "/// in solid). Not const because Dart's equal_keys_in_const_map lint\n" +
    "/// flags the expanded duplicates; at runtime the later spread wins.\n" +
    "final Map<String, String> heroiconsAllIcons = {\n" +
    "  ...heroiconsIcons,\n" +
    "  ...heroiconsSolidIcons,\n" +
    "};\n";

  await mkdir(dirname(OUT_FILE), { recursive: true });
  await writeFile(OUT_FILE, output, "utf8");

  const total = outline.rows.length + solid20.rows.length + solid24.rows.length + solid16.rows.length;
  console.log(`Generated ${outline.rows.length} outline (24) + ${solid20.rows.length} solid20 (20→24) + ${solid24.rows.length} solid24 + ${solid16.rows.length} solid16 (16→24) = ${total} icons in ${OUT_FILE}`);
  const skippedGroups = [
    outline.skipped.length ? `outline:${outline.skipped.length}` : "",
    solid20.skipped.length ? `solid20:${solid20.skipped.length}` : "",
    solid24.skipped.length ? `solid24:${solid24.skipped.length}` : "",
    solid16.skipped.length ? `solid16:${solid16.skipped.length}` : "",
  ].filter(Boolean).join(", ");
  if (skippedGroups) console.log(`Skipped groups: ${skippedGroups}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
